
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btglrgvobasvaqajezyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Z2xyZ3ZvYmFzdmFxYWplenl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzY4MDksImV4cCI6MjA2NzcxMjgwOX0.jK0upz-3IooBPWTWWN7MlsrS6x5J6WwR-mu6rwJhd-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
